### ISSUE TITLE
You're never on Discord

### ISSUE THREAD

**Issue by Quackster** [igorlira/foo#1]
Hi Igor,

I'm sorry for creating an issue on a random repository you have but I've found literally no other way to contact you, you're always offline on discord. ☹️ 

Please speak with me: Alex#3441

Thank you

**Comment by igorlira** [comment]
Hey! I don’t really use Discord that much so that’s why. I tried messaging you there but it didn’t let me because we’re not friends or whatever. I’m more active on Twitter (@igorlira) so feel free to send me a DM there.

**Comment by JairKuma** [comment]
Igor add me in Twitter, I'd like to talk with you @Alito21424674
